/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViA.BotonConfigUsuario.VistaPConfUsuario.AgregarProductos;

import MoA.OjetosCnn.ProductoDao;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author elmej
 */
public class VAgregarProducto extends javax.swing.JFrame {

    /**
     * Creates new form VAgregarProducto
     */
    public VAgregarProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Nombre_Agregar_P = new javax.swing.JTextField();
        Precio_Agregar_P = new javax.swing.JTextField();
        Ganancia_Agregar_P = new javax.swing.JTextField();
        Distribuidor_Agregar_P = new javax.swing.JTextField();
        Codigo_Agregar_P = new javax.swing.JTextField();
        Itebis_Agregar_P = new javax.swing.JTextField();
        Fecha_Agregar_P = new javax.swing.JTextField();
        Max_Agregar_P = new javax.swing.JTextField();
        Min_Agregar_P = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Detalles_Agregar_P = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        Nombre_Itebis_Adicional = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Precio");

        jLabel3.setText("Ganancia");

        jLabel4.setText("Distribuidor");

        jLabel5.setText("Codigo de barras");

        jLabel6.setText("ITBIS ADICIONAL %");

        jLabel7.setText("Max");

        jLabel8.setText("Fecha de caducidad");

        jLabel9.setText("Min");

        jLabel10.setText("Detalles");

        Nombre_Agregar_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_Agregar_PActionPerformed(evt);
            }
        });

        Precio_Agregar_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Precio_Agregar_PActionPerformed(evt);
            }
        });

        Ganancia_Agregar_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ganancia_Agregar_PActionPerformed(evt);
            }
        });

        Distribuidor_Agregar_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Distribuidor_Agregar_PActionPerformed(evt);
            }
        });

        Codigo_Agregar_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Codigo_Agregar_PActionPerformed(evt);
            }
        });

        Itebis_Agregar_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Itebis_Agregar_PActionPerformed(evt);
            }
        });

        Fecha_Agregar_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fecha_Agregar_PActionPerformed(evt);
            }
        });

        Max_Agregar_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Max_Agregar_PActionPerformed(evt);
            }
        });

        Min_Agregar_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Min_Agregar_PActionPerformed(evt);
            }
        });

        Detalles_Agregar_P.setColumns(20);
        Detalles_Agregar_P.setRows(5);
        jScrollPane1.setViewportView(Detalles_Agregar_P);

        jLabel11.setText("Nombre del ITBIS");

        Nombre_Itebis_Adicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_Itebis_AdicionalActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre_Agregar_P, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Precio_Agregar_P, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ganancia_Agregar_P, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Distribuidor_Agregar_P, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Max_Agregar_P, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                .addComponent(Min_Agregar_P, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(Fecha_Agregar_P, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(113, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Itebis_Agregar_P, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Nombre_Itebis_Adicional))
                            .addComponent(Codigo_Agregar_P, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Nombre_Agregar_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Precio_Agregar_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Ganancia_Agregar_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Distribuidor_Agregar_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Codigo_Agregar_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Itebis_Agregar_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(Nombre_Itebis_Adicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Fecha_Agregar_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Max_Agregar_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Min_Agregar_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Nombre_Agregar_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_Agregar_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_Agregar_PActionPerformed

    private void Precio_Agregar_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Precio_Agregar_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Precio_Agregar_PActionPerformed

    private void Ganancia_Agregar_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ganancia_Agregar_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ganancia_Agregar_PActionPerformed

    private void Distribuidor_Agregar_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Distribuidor_Agregar_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Distribuidor_Agregar_PActionPerformed

    private void Codigo_Agregar_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Codigo_Agregar_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Codigo_Agregar_PActionPerformed

    private void Itebis_Agregar_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Itebis_Agregar_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Itebis_Agregar_PActionPerformed

    private void Fecha_Agregar_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fecha_Agregar_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fecha_Agregar_PActionPerformed

    private void Max_Agregar_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Max_Agregar_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Max_Agregar_PActionPerformed

    private void Min_Agregar_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Min_Agregar_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Min_Agregar_PActionPerformed

    private void Nombre_Itebis_AdicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_Itebis_AdicionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_Itebis_AdicionalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        ProductoDao pp=new ProductoDao();
        
        pp.agregarProducto(this);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VAgregarProducto().setVisible(true);
            }
        });
    }

    public JTextField getCodigo_Agregar_P() {
        return Codigo_Agregar_P;
    }

    public void setCodigo_Agregar_P(JTextField Codigo_Agregar_P) {
        this.Codigo_Agregar_P = Codigo_Agregar_P;
    }

    public JTextArea getDetalles_Agregar_P() {
        return Detalles_Agregar_P;
    }

    public void setDetalles_Agregar_P(JTextArea Detalles_Agregar_P) {
        this.Detalles_Agregar_P = Detalles_Agregar_P;
    }

    public JTextField getDistribuidor_Agregar_P() {
        return Distribuidor_Agregar_P;
    }

    public void setDistribuidor_Agregar_P(JTextField Distribuidor_Agregar_P) {
        this.Distribuidor_Agregar_P = Distribuidor_Agregar_P;
    }

    public JTextField getFecha_Agregar_P() {
        return Fecha_Agregar_P;
    }

    public void setFecha_Agregar_P(JTextField Fecha_Agregar_P) {
        this.Fecha_Agregar_P = Fecha_Agregar_P;
    }

    public JTextField getGanancia_Agregar_P() {
        return Ganancia_Agregar_P;
    }

    public void setGanancia_Agregar_P(JTextField Ganancia_Agregar_P) {
        this.Ganancia_Agregar_P = Ganancia_Agregar_P;
    }

    public JTextField getItebis_Agregar_P() {
        return Itebis_Agregar_P;
    }

    public void setItebis_Agregar_P(JTextField Itebis_Agregar_P) {
        this.Itebis_Agregar_P = Itebis_Agregar_P;
    }

    public JTextField getMax_Agregar_P() {
        return Max_Agregar_P;
    }

    public void setMax_Agregar_P(JTextField Max_Agregar_P) {
        this.Max_Agregar_P = Max_Agregar_P;
    }

    public JTextField getMin_Agregar_P() {
        return Min_Agregar_P;
    }

    public void setMin_Agregar_P(JTextField Min_Agregar_P) {
        this.Min_Agregar_P = Min_Agregar_P;
    }

    public JTextField getNombre_Agregar_P() {
        return Nombre_Agregar_P;
    }

    public void setNombre_Agregar_P(JTextField Nombre_Agregar_P) {
        this.Nombre_Agregar_P = Nombre_Agregar_P;
    }

    public JTextField getPrecio_Agregar_P() {
        return Precio_Agregar_P;
    }

    public void setPrecio_Agregar_P(JTextField Precio_Agregar_P) {
        this.Precio_Agregar_P = Precio_Agregar_P;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTextField getNombre_Itebis_Adicional() {
        return Nombre_Itebis_Adicional;
    }

    public void setNombre_Itebis_Adicional(JTextField Nombre_Itebis_Adicional) {
        this.Nombre_Itebis_Adicional = Nombre_Itebis_Adicional;
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Codigo_Agregar_P;
    private javax.swing.JTextArea Detalles_Agregar_P;
    private javax.swing.JTextField Distribuidor_Agregar_P;
    private javax.swing.JTextField Fecha_Agregar_P;
    private javax.swing.JTextField Ganancia_Agregar_P;
    private javax.swing.JTextField Itebis_Agregar_P;
    private javax.swing.JTextField Max_Agregar_P;
    private javax.swing.JTextField Min_Agregar_P;
    private javax.swing.JTextField Nombre_Agregar_P;
    private javax.swing.JTextField Nombre_Itebis_Adicional;
    private javax.swing.JTextField Precio_Agregar_P;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
